### ISSUE TITLE
Wait Seconds is Incorrect  When Program Execution is Slowed

### ISSUE THREAD

**Issue by MerlinofMines** [MerlinofMines/EasyCommands#120]
Currently the Wait command assumes (poorly) that you are always running at 60 ticks / second.  If you slow down the program execution, this causes waits to be way longer than intended.

The wait time, in ticks, should be calculated based on the runtime frequency instead of assumed, so that wait <seconds> is not effected (other than maybe precision) when the runtime frequency is lowered.

Don't forget to update the debugging docs to describe the new behavior.  Also, any issues with how the current "wait ticks" works?  Likely "ticks" will still be actual ticks (regardless of frequency) but seconds will adjust based on frequency?

**Comment by jgersti** [comment]
Instead of assuming a frequency and counting ticks you can use `Runtime.TimeSinceLastRun` to get a more accurate behaviour.
This property returns a TimeSpan.

In general it is bad idea to throttle a script that needs to run regularly by setting a lower frequency, since there is no way of knowing when the script is active again. (see: [MDK Wiki: Continuous Running No Timers Needed](https://github.com/malware-dev/MDK-SE/wiki/Continuous-Running-No-Timers-Needed#important-the-number-of-ticks-until-next-run-is-not-guaranteed)).

**Comment by MerlinofMines** [comment]
Thanks for the suggestion, let's look into this.  We still need to deal with ticks though for conditional checks that are not time relevant but tick relevant ("wait until myCondition is true").  We'll need to think how we can combine these in a nice way.
