### ISSUE TITLE
Suspensions are missing a property to disable steering

### ISSUE THREAD

**Issue by jgersti** [MerlinofMines/EasyCommands#175]
Current workaround is setting the steering limit to 0. Also the bahavior of the steering limit and steering override are suprising since the value ranges are switched compared to the ingame interface.

**Comment by MerlinofMines** [comment]
Interesting on the values being surprising.  I did a poll with some of my buddies and we agreed that -45 = Left, 0 = straight, 45 = Right seemed reasonable.  Maybe I missed something about how limits are set and this is a bug?

As for disabling steering, I think this definitely indicates that we should add a new "Steering" property. 

setting steering to true/false will enable/disabling steering.
reversing steering will reverse steering.

```
turn off "My Wheel" steering
turn on "My Wheel" steering
reverse "My Wheel" steering
```

Related to #176

**Comment by jgersti** [comment]
what is meant is that ingame steering limit is in the range `-44.5..44.5` and the steering override is in the range `-100..100`.
In the script this is reversed.

Another issue is that as far as i could gleam from script from whiplash141 and the discussion on the keen discord if you override the velocity and steering on a wheel directly with a script the orientation of the wheels instead of the cockpit orientation is used.

**Comment by MerlinofMines** [comment]
I see.  Ya, a couple of challenges here which we can address.

First, the "Angle" property definitely should accept an angle, in degrees.  ```set "Test Wheel" angle to 45``` should be 45°, not 45%

We could add Override property and map the values from -100..100 onto the correct range. I think we'd need to make it directional to indicate "left/right = steering override, forward/backwards (up/down?) = propulsion

Second, while the in game steering angle is presented in degrees, the ingame scripting library uses values from 0 - 1.  Agree it'd be better to map these back to angles so that getting/setting the limits matches the angles you see in game.
