### ISSUE TITLE
Suspensions are missing properties to invert steering and propulsion

### ISSUE THREAD

**Issue by jgersti** [MerlinofMines/EasyCommands#176]

**Comment by MerlinofMines** [comment]
hmm, perhaps we use the "Reverse" functionality.

reverse the "Test Wheel" steering.

Not sure yet if it's reasonable to re-use the "Angle" property for steering and "Velocity" property for propulsion.

In either case, I think we want to use "reverse" on the property to indicate to inverse.

See PistonBlockHandlers for an example PropertyHandler that overrides the "Reverse" ability.

**Comment by jgersti** [comment]
steering is not a property yet. introducing it would enable to clean up some rather funny looking syntax at a cost of breaking old behavior.

But these two properties as toggles and are not really actions so your propsed syntax would violate atleast my expectation what is happening.

**Comment by MerlinofMines** [comment]
"reverse" is currently considered an action keyword.  We can also add "invert" as a keyword.

I'm not too concerned about breaking the funny syntax if it gives an easier syntax.  We make sure to reference this in the modified behavior section.  Otherwise, a user's script is only broken if they chose to upgrade to the newer version of the script.

As long as we don't remove functionality I think it's OK.
